select * from public.users;
select * from public.contribution;
select * from public.site;
select * from public.city;
select * from public.culture;
select * from public.user_contribution_interest
select * from public.user_site_interest;
select * from public.user_city_interest;
select * from public.user_culture_interest;
